### ISSUE TITLE
Threaded comment

### ISSUE THREAD

**Issue by khanshakeeb** [RomainLanz/laravel-commentable-deprecated#1]
Hi,

I just need to know whether this plugin will support multi-level comments?

**Comment by RomainLanz** [comment]
I can't do that right know, but I will delete this repository and write another package with threaded comment soon.

Maybe in two weeks, can you wait?

**Comment by khanshakeeb** [comment]
@RomainLanz or if you want me to collaborate then I am happily do that.

**Comment by RomainLanz** [comment]
You can do a PR if you want :)

**Comment by RomainLanz** [comment]
But as I said, a new version of this package will come at the end of the month. And this will support threaded comments. :smile:

**Comment by RomainLanz** [comment]
@khanshakeeb
I just write a new version here https://github.com/RomainLanz/laravel-commentable.

I will delete this repository in one month.

**Comment by khanshakeeb** [comment]
@RomainLanz thanks for updating me up

**Comment by RomainLanz** [comment]
No problem :)

cc @anzap
